dataUrl: data
webdavUrl: webdav

title: >-
  PURE3D - An Infrastructure
  for Publication and Preservation
  of 3D Scholarship

heading: Pure 3D website
iconFile: icon.png
faviconFile: favicon.ico

database: pure3d
mongoHost: mongodb
mongoPort: 27017

siteCrit:
  name: "site"

modelzFile: models.zip

editionSettingsTemplate:
  authorTool:
    name: «viewer»
    version: «version»
    sceneFile: «scene»

representations:
  isVisible:
    false: "hidden"
    true: "public"
  isPublished:
    false: "in progress"
    true: "published"

css:
  isVisible:
    false: "wip"
    true: "public"
  isPublished:
    false: "wip"
    true: "published"

icons:
  assign: "⊫"
  download: "⇲"
  edit_cancel: "❌"
  edit_save: "✅"
  edit_update: "✎"
  edit_assign: "♺"
  edit_insert: "✚"
  edit_link: "⚭"
  chain: "⚭"
  check: "✔︎"
  create: "✚"
  cross: "✘"
  delete: "✖︎"
  devel: "⚒︎"
  exist: "✔︎"
  info: "ℹ︎"
  missing: "☒"
  noexist: "∅"
  noicon: "☹︎"
  none: "○"
  ok: "↩︎"
  prov: "⌚︎"
  read: "⎚"
  refresh: "♺"
  reset: "↩︎"
  update: "✎"
  upload: "↑"

iconTips:
  edit_cancel: "reset to last saved value"
  edit_save: "save and quit"
  edit_update: "edit this value"
  edit_assign: "assign user role(s)"
  edit_insert: "add someone or something"
  edit_link: "link someone to this"
