dataUrl: data
webdavUrl: webdav

# prod must be the first runMode: production

runModes:
  - prod
  - custom
  - pilot
  - test

title: >-
  PURE3D - An Infrastructure
  for Publication and Preservation
  of 3D Scholarship

heading: Pure 3D website
iconFile: icon.png
faviconFile: favicon.ico

database: pure3d

siteCrit:
  name: "site"

modelzFile: models.zip
tocFile: toc.html
dbFile: db.json
published: published
article: article
media: media
backPrefix: frompub
authorLabel: the author environment

editionSettingsTemplate:
  authorTool:
    name: Â«viewerÂ»
    version: Â«versionÂ»
    sceneFile: Â«sceneÂ»

representations:
  isVisible:
    false: "hidden"
    true: "public"
  isPublished:
    false: "in progress"
    true: "published"

css:
  isVisible:
    false: "wip"
    true: "public"
  isPublished:
    false: "wip"
    true: "published"

icons:
  assign: "âŠ«"
  download: "â‡²"
  kwmanage_cancel: "âŒ"
  kwmanage_save: "âœ…"
  edit_cancel: "âŒ"
  edit_save: "âœ…"
  edit_update: "âœ"
  edit_assign: "â™º"
  edit_insert: "âœš"
  edit_link: "âš­"
  chain: "âš­"
  check: "âœ”ï¸"
  create: "âœš"
  cross: "âœ˜"
  delete: "âœ–ï¸"
  devel: "âš’ï¸"
  exist: "âœ”ï¸"
  info: "â„¹ï¸"
  missing: "â˜’"
  noexist: "âˆ…"
  noicon: "â˜¹ï¸"
  none: "â—‹"
  ok: "â†©ï¸"
  prov: "âŒšï¸"
  read: "âš"
  refresh: "â™º"
  reset: "â†©ï¸"
  update: "âœ"
  upload: "â†‘"
  precheck: "â‰ï¸"
  publish: "ğŸ…¿ï¸"
  publishf: "ğŸ…¿ï¸â—ï¸"
  republish: "â†ªï¸"
  republishf: "â†ªï¸â—ï¸"
  unpublish: "â›”ï¸"

iconTips:
  edit_cancel: "reset to last saved value"
  edit_save: "save and quit"
  edit_update: "edit this value"
  edit_assign: "assign user role(s)"
  edit_insert: "add someone or something"
  edit_link: "link someone to this"

limits:
  sizeUnit: MB
  sizeUnitSize: 1048576
  sizeUnits: 1024
  sizeUnitsOptimistic: 4096

dontCompress:
  - png
  - jpg
  - zip
  - glb
  - mp3
  - mp4
  - wav
